import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSearchQuery } from '../src/generated/graphql'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  let { data } = useSearchQuery({
    variables: {
      query: "hsr"
    }
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          !data ? null :
            data.nobroker.searchCity.predictions.map(
              (prediction) => {
                prediction.placeId
              }
            )
        }
      </main>
    </div>
  )
}

export default Home
